"""add hotels

Revision ID: d4dff9b1046a
Revises: 2a46f9f9d4d2
Create Date: 2025-02-10 10:25:58.432011

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d4dff9b1046a"
down_revision: Union[str, None] = "2a46f9f9d4d2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("hotel", sa.Column("services", sa.String(), nullable=False))
    op.add_column("hotel", sa.Column("rooms_quantity", sa.Integer(), nullable=False))
    op.add_column("hotel", sa.Column("image_id", sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("hotel", "image_id")
    op.drop_column("hotel", "rooms_quantity")
    op.drop_column("hotel", "services")
    # ### end Alembic commands ###
