"""fix user

Revision ID: e0755fdc7645
Revises: 28a4f09a46dd
Create Date: 2025-02-10 11:28:19.712230

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e0755fdc7645"
down_revision: Union[str, None] = "28a4f09a46dd"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "username")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user", sa.Column("username", sa.VARCHAR(), autoincrement=False, nullable=False)
    )
    # ### end Alembic commands ###
